In [5]:
import numpy as np


In [6]:
from time import process_time

In [7]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)
    

0.0


In [8]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [9]:
type(list1)

list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [11]:
type(np_array)

numpy.ndarray

In [12]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
 b.shape
    

(2, 4)

In [15]:
a.shape

(5,)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [18]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


numpy array with random value

In [25]:
d = np.random.random((3,4))
print(d)

[[0.16584882 0.4647156  0.02324074 0.25758098]
 [0.0566572  0.24985173 0.2996145  0.67946159]
 [0.63537829 0.90915815 0.28626283 0.18230922]]


In [26]:
c = np.random.randint(10,100,(3,5))
print(c)

[[43 59 83 29 94]
 [81 64 32 27 89]
 [16 48 67 18 33]]


In [28]:
a = np.linspace(10,30,6)
print(a)

[10. 14. 18. 22. 26. 30.]


In [29]:
 e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [30]:
l = [10,20,30,40,50]
n = np.asarray(l)
print(n)
type(n)

[10 20 30 40 50]


numpy.ndarray

In [32]:
print(n.ndim)

1


In [34]:
print(n.size)

5


In [35]:
print(n.dtype)

int32


Mathematical operations on a np array

In [36]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
print(l1 + l2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [37]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [43]:
print(a)
print(b)

[[5 1 6]
 [5 8 5]
 [7 6 8]]
[[18 18 17]
 [14 12 15]
 [10 18 11]]


In [44]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[23 19 23]
 [19 20 20]
 [17 24 19]]
[[-13 -17 -11]
 [ -9  -4 -10]
 [ -3 -12  -3]]
[[ 90  18 102]
 [ 70  96  75]
 [ 70 108  88]]
[[0.27777778 0.05555556 0.35294118]
 [0.35714286 0.66666667 0.33333333]
 [0.7        0.33333333 0.72727273]]


In [45]:
print(np.add(a,b))

[[23 19 23]
 [19 20 20]
 [17 24 19]]


In [48]:
print(np.subtract(a,b))

[[-13 -17 -11]
 [ -9  -4 -10]
 [ -3 -12  -3]]


In [49]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 4 9]
 [2 7 0]]
(2, 3)


In [50]:
T = np.transpose(array)
print(T)

[[5 2]
 [4 7]
 [9 0]]


In [51]:
print(T.shape)

(3, 2)


importing the data from a csv file to pandas dataframe

In [55]:
import pandas as pd
D = pd.read_csv(r"C:\Users\shweta\Downloads\nba.csv")

In [57]:
D

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

RESHAPING ARRAY

In [58]:
A = np.random.randint(0,10,(2,3))
print(A)

[[6 0 6]
 [6 1 5]]


In [59]:
b = A.reshape(3,2)
print(b)

[[6 0]
 [6 6]
 [1 5]]
